version: '3.9'

services:
  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}-nginx
    image: nginx:alpine
#    загуглить
    volumes:
      - ./.devenv/nginx:/etc/nginx/conf.d:ro
      - ./.devenv/log/nginx:/var/log/nginx:rw
      - .:/app:delegated
    ports:
      - "${EXPOSE_PORT:-8080}:80"
    restart: always

  php:
    container_name: ${COMPOSE_PROJECT_NAME}-php
    image: php:8.1-fpm-alpine
    deploy:
        resources:
            limits:
                #cpus: '0.001'
                memory: 2000M
            reservations:
                #cpus: '0.0001'
                memory: 100M
    volumes:
      - .:/app
    environment:
      - PHP_XDEBUG_MODE=debug
      - PHP_XDEBUG_START_WITH_REQUEST=trigger
      - PHP_XDEBUG_CLIENT_HOST=host.docker.internal
      - PHP_XDEBUG_CLIENT_PORT=9005
      - PHP_XDEBUG_IDEKEY=PHPSTORM
    restart: always

